import type { Metadata } from "next";
import Link from "next/link";
import { LegalLayout, H2, P, UL } from "@/components/landing/legal-layout";

export const metadata: Metadata = {
  title: "Privacy Policy — WhatsappAutomate",
  description:
    "How WhatsappAutomate collects, uses, and protects the data of businesses and their customers.",
};

const COMPANY_NAME = "WhatsappAutomate";
const CONTACT_EMAIL = "hiveofsolutionspro@gmail.com";

export default function PrivacyPage() {
  return (
    <LegalLayout title="Privacy Policy" effectiveDate="June 15, 2026">
      <P>
        This Privacy Policy describes how {COMPANY_NAME} (&ldquo;we&rdquo;,
        &ldquo;us&rdquo;, &ldquo;our&rdquo;) collects, uses, stores, and shares
        information when you use our WhatsApp automation platform (the
        &ldquo;Service&rdquo;). By using the Service you agree to the terms
        described below.
      </P>

      <H2>1. Who this policy covers</H2>
      <P>
        We collect two kinds of data, and this policy covers both:
      </P>
      <UL>
        <li>
          <strong>Business users</strong> — the people and businesses that sign
          up for {COMPANY_NAME} to automate their WhatsApp conversations.
        </li>
        <li>
          <strong>End customers</strong> — the individuals who message a business
          on WhatsApp and whose messages are processed by our AI on the
          business&apos;s behalf.
        </li>
      </UL>

      <H2>2. Information we collect from business users</H2>
      <UL>
        <li>
          <strong>Account information:</strong> name, email address, business
          name, industry, and password (hashed).
        </li>
        <li>
          <strong>WhatsApp credentials:</strong> Meta WhatsApp Business phone
          number ID, display number, and access token, which you voluntarily
          provide in Settings to enable message processing.
        </li>
        <li>
          <strong>Configuration:</strong> AI persona name, tone, language
          preference, and any custom system prompt you configure.
        </li>
        <li>
          <strong>Usage data:</strong> log records of dashboard activity,
          message counts, and feature usage.
        </li>
        <li>
          <strong>Billing information:</strong> for paid plans, billing handled
          by our payment processor — we never store full card details.
        </li>
      </UL>

      <H2>3. Information we collect from end customers</H2>
      <UL>
        <li>
          <strong>WhatsApp identifiers:</strong> phone number (in E.164 format)
          and WhatsApp profile name as supplied by Meta.
        </li>
        <li>
          <strong>Message content:</strong> the text content of inbound messages
          sent to a business that uses {COMPANY_NAME}, and outbound replies
          generated by our AI or sent by the business owner.
        </li>
        <li>
          <strong>Extracted attributes:</strong> structured data inferred by our
          AI from the conversation, such as budget, area of interest, intent,
          and qualification stage, used to help the business respond.
        </li>
      </UL>

      <H2>4. How we use the information</H2>
      <UL>
        <li>To operate the Service — route messages, generate AI replies, and surface leads to the business.</li>
        <li>To provide a dashboard showing conversation history and extracted lead data to the business that owns those conversations.</li>
        <li>To improve product quality, fix bugs, and monitor abuse.</li>
        <li>To send transactional emails (account verification, billing receipts, security notifications).</li>
        <li>To comply with legal obligations and respond to lawful requests.</li>
      </UL>
      <P>
        We do <strong>not</strong> sell personal data to third parties. We do
        not use end-customer message content to train AI models.
      </P>

      <H2>5. Third-party services we share data with</H2>
      <P>
        We share the minimum data needed to provide the Service with these
        sub-processors:
      </P>
      <UL>
        <li>
          <strong>Meta Platforms, Inc.</strong> — to send and receive messages
          via the WhatsApp Cloud API. Messages and metadata are routed through
          Meta&apos;s infrastructure under their own policies (
          <a
            href="https://www.whatsapp.com/legal/privacy-policy"
            target="_blank"
            rel="noopener noreferrer"
            className="text-primary hover:underline"
          >
            WhatsApp Privacy Policy
          </a>
          ).
        </li>
        <li>
          <strong>Google LLC (Gemini API)</strong> — message content is sent to
          Google&apos;s Gemini model to generate replies and extract structured
          data. Google does not use this content for model training (
          <a
            href="https://ai.google.dev/gemini-api/terms"
            target="_blank"
            rel="noopener noreferrer"
            className="text-primary hover:underline"
          >
            Gemini API Terms
          </a>
          ).
        </li>
        <li>
          <strong>Supabase Inc.</strong> — hosts our Postgres database
          containing all account, conversation, and lead data, with row-level
          security enforced per business tenant.
        </li>
        <li>
          <strong>Vercel Inc.</strong> — hosts our application code and serves
          web traffic.
        </li>
      </UL>

      <H2>6. Data retention</H2>
      <UL>
        <li>Account data is retained for the lifetime of your account.</li>
        <li>
          Conversations and leads are retained while the originating business
          account is active.
        </li>
        <li>
          Upon account deletion, your data and all end-customer data tied to
          your account is permanently deleted within 30 days, except where
          retention is required by law.
        </li>
      </UL>

      <H2>7. Your rights</H2>
      <P>You have the right to:</P>
      <UL>
        <li>Access the personal data we hold about you.</li>
        <li>Correct inaccurate or incomplete data.</li>
        <li>Request deletion of your account and associated data.</li>
        <li>
          Export your conversation and lead data in a machine-readable format.
        </li>
        <li>
          Withdraw consent for processing where consent is the legal basis.
        </li>
      </UL>
      <P>
        To exercise any of these rights, email us at{" "}
        <a
          href={`mailto:${CONTACT_EMAIL}`}
          className="text-primary hover:underline"
        >
          {CONTACT_EMAIL}
        </a>
        . We respond within 30 days.
      </P>

      <H2>8. How to delete your data</H2>
      <P>
        Business owners can delete their account at any time from
        Settings &rarr; Danger zone &rarr; Delete account. This permanently
        removes all data associated with the account, including conversations
        and leads, within 30 days. To request deletion of end-customer data
        outside of the dashboard, contact the business that owns those
        conversations or email us at{" "}
        <a
          href={`mailto:${CONTACT_EMAIL}`}
          className="text-primary hover:underline"
        >
          {CONTACT_EMAIL}
        </a>
        .
      </P>

      <H2>9. Security</H2>
      <P>
        We use industry-standard practices to protect your data: HTTPS for all
        traffic, encrypted credential storage, row-level security in our
        database, and signed webhook payloads. No system is perfectly secure,
        so we encourage you to use a strong password and enable
        multi-factor authentication where available.
      </P>

      <H2>10. International data transfers</H2>
      <P>
        Your data may be processed in countries other than your own,
        including the United States and the European Union. We rely on
        standard contractual safeguards offered by our sub-processors.
      </P>

      <H2>11. Children</H2>
      <P>
        Our Service is not intended for individuals under the age of 16. We do
        not knowingly collect data from children. If you believe we have
        collected data from a minor, contact us so we can delete it.
      </P>

      <H2>12. Changes to this policy</H2>
      <P>
        We may update this policy from time to time. When we do, we will update
        the effective date at the top of this page and, for material changes,
        send a notice to your account email at least 30 days in advance.
      </P>

      <H2>13. Contact</H2>
      <P>
        Questions about this policy? Email{" "}
        <a
          href={`mailto:${CONTACT_EMAIL}`}
          className="text-primary hover:underline"
        >
          {CONTACT_EMAIL}
        </a>
        {" "}or visit our{" "}
        <Link href="/contact" className="text-primary hover:underline">
          contact page
        </Link>
        .
      </P>
    </LegalLayout>
  );
}
